version: '3.9'

services:
  fastapi-agent:
    build: .
    container_name: fastapi-agent
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: always

  # Locust Master
  locust-master:
    image: locustio/locust:2.31.2
    container_name: locust-master
    command: >
      -f /mnt/locust/locustfile.py --master --host http://fastapi-agent:8000
    ports:
      - "8089:8089"  # Web UI
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    depends_on:
      - fastapi-agent

  # Locust Worker(s)
  locust-worker:
    image: locustio/locust:2.31.2
    container_name: locust-worker
    command: >
      -f /mnt/locust/locustfile.py --worker --master-host=locust-master
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    depends_on:
      - locust-master
